name: Periodic Ping

on:
  schedule:
    - cron: '*/14 * * * *'  # Run every 14 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
    - name: Ping server
      run: |
        curl -sS --retry 3 https://your-render-app-url.onrender.com/keepalive
